print ("Hello from Pranjal")
print("Hello from Rahul")
print("Hello from prem")
print("Hello from vaibhav")
print("Hello from Nilay - New github account")
print("Hello from Pruthviraj")
print("Hello from Shubham")
